<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /Users/monish/src/civi-extensions/chfunds/xml/schema/CRM/Chfunds/OptionValueCH.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:eef887fe736787d703357d6ce6ddfd1e)
 */

/**
 * Database access object for the OptionValueCH entity.
 */
class CRM_Chfunds_DAO_OptionValueCH extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_option_value_ch';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique OptionValueCH ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Option Group
   *
   * @var int
   */
  public $option_group_id;

  /**
   * @var string
   */
  public $value;

  /**
   * Foreign key to civicrm_financial_type
   *
   * @var int
   */
  public $financial_type_id;

  /**
   * @var bool
   */
  public $is_enabled_in_ch;

  /**
   * @var int
   */
  public $parent_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_option_value_ch';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'option_group_id', 'civicrm_option_group', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'financial_type_id', 'civicrm_financial_type', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'parent_id', 'civicrm_option_value_ch', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('Unique OptionValueCH ID'),
          'required' => TRUE,
          'where' => 'civicrm_option_value_ch.id',
          'table_name' => 'civicrm_option_value_ch',
          'entity' => 'OptionValueCH',
          'bao' => 'CRM_Chfunds_DAO_OptionValueCH',
          'localizable' => 0,
        ],
        'option_group_id' => [
          'name' => 'option_group_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('FK to Option Group'),
          'where' => 'civicrm_option_value_ch.option_group_id',
          'table_name' => 'civicrm_option_value_ch',
          'entity' => 'OptionValueCH',
          'bao' => 'CRM_Chfunds_DAO_OptionValueCH',
          'localizable' => 0,
        ],
        'value' => [
          'name' => 'value',
          'type' => CRM_Utils_Type::T_STRING,
          'maxlength' => 255,
          'description' => ts('Value of CH Fund'),
          'where' => 'civicrm_option_value_ch.value',
          'table_name' => 'civicrm_option_value_ch',
          'entity' => 'OptionValueCH',
          'bao' => 'CRM_Chfunds_DAO_OptionValueCH',
          'localizable' => 0,
        ],
        'financial_type_id' => [
          'name' => 'financial_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('Foreign key to civicrm_financial_type'),
          'where' => 'civicrm_option_value_ch.financial_type_id',
          'table_name' => 'civicrm_option_value_ch',
          'entity' => 'OptionValueCH',
          'bao' => 'CRM_Chfunds_DAO_OptionValueCH',
          'localizable' => 0,
        ],
        'is_enabled_in_ch' => [
          'name' => 'is_enabled_in_ch',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Is Enabled on CH'),
          'import' => TRUE,
          'where' => 'civicrm_option_value_ch.is_enabled_in_ch',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_option_value_ch',
          'entity' => 'OptionValueCH',
          'bao' => 'CRM_Chfunds_DAO_OptionValueCH',
          'localizable' => 0,
        ],
        // Added new column 'parent_id' for data table 'civicrm_option_value_ch'
        'parent_id' => [
          'name' => 'parent_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('parent id of CH option value '),
          'where' => 'civicrm_option_value_ch.parent_id',
          'table_name' => 'civicrm_option_value_ch',
          'entity' => 'OptionValueCH',
          'bao' => 'CRM_Chfunds_DAO_OptionValueCH',
          'localizable' => 0,
        ]
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'option_value_ch', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'option_value_ch', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
